config/routes.rb
Rails.application.routes.draw do

  #GOT RID OF IN CHECKPOINT 21-resources :topics #didn't pass in any action arguments into controller generator; resources creates seven standard CRUD routes for me (index, create, new, edit, show, update PUT, update PATCH, destroy)
  #GOT RID OF IN CHECKPOINT 21-resources :posts #call the resources method and pass it a symbol; instructs Rails to create post routes for creating, updating, viewing, and deleting instances of Post

  resources :topics do
    #pass resources :posts to the resources :topics block. This nests the post routes under the topic routes
    resources :posts, except: [:index]
  end

  #create user routes for new and create actions; only hash key will prevent Rails from creating unnecessary routes
  resources :users, only: [:new, :create]

  resources :sessions, only: [:new, :create, :destroy]

  post 'users/confirm' => 'users#confirm'

  get 'about' => 'welcome#about' #remove get "welcome/index" because we've declared the index view as the root view; also modify the about route to allow users to visit /about, rather than /welcome/about

  root 'welcome#index'#root method allows us to declare the default page; index will be the first thing we see

end

#TO GET ALL ROUTES IN TERMINAL...
  ##rails routes
#TO GET TOPICS ROUTES
  ##rails routes | grep topics
#TO GET USER ROUTES
  ##rails routes | grep user
#TO GET SESSION ROUTES
    ##rails routes | grep session

app/models/topic.rb
class Topic < ApplicationRecord
  #Because comments already depend on posts, they will also be deleted when a topic is deleted.
  has_many :posts, dependent: :destroy

  validates :name, length: { minimum: 5 }, presence: true
  validates :description, length: { minimum: 15 }, presence: true

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
    def index
        @topics = Topic.all
    end

    def show
        @topic = Topic.find(params[:id])
    end

    def new
        @topic = Topic.new
    end  

    def create
        @topic = Topic.new
        @topic.name = params[:topic][:name]
        @topic.description = params[:topic][:description]
        @topic.public = params[:topic][:public]
    
        if @topic.save
          redirect_to @topic, notice: "Topic was saved successfully."
        else
          flash.now[:alert] = "Error creating topic. Please try again."
          render :new
        end
    end

    def edit
        @topic = Topic.find(params[:id])
    end

    def update
        @topic = Topic.find(params[:id])
    
        @topic.name = params[:topic][:name]
        @topic.description = params[:topic][:description]
        @topic.public = params[:topic][:public]
    
        if @topic.save
           flash[:notice] = "Topic was updated."
          redirect_to @topic
        else
          flash.now[:alert] = "Error saving topic. Please try again."
          render :edit
        end
    end

    def destroy
        @topic = Topic.find(params[:id])
    
        if @topic.destroy
          flash[:notice] = "\"#{@topic.name}\" was deleted successfully."
          redirect_to action: :index #redirect_to action: :index is the same as redirect_to topics_path because topics_path routes to the index action per Rails' resourceful routing
        else
          flash.now[:alert] = "There was an error deleting the topic."
          render :show
        end
    end

end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<!--Partial for topics views; underscore before file name lets rails know it's a partial-->
<!--Partials can use instance variables, but for cleanliness and reusability it's better to use locals -->

<%= form_for [topic] do |f| %>
  <% if topic.errors.any? %>
    <div class="alert alert-danger">
      <h4><%= pluralize(topic.errors.count, "error") %>.</h4>
      <ul>
        <% topic.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_group_tag(topic.errors[:name]) do %>
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control', placeholder: "Enter topic name" %>
  <% end %>

  <%= form_group_tag(topic.errors[:description]) do %>
    <%= f.label :description %>
    <%= f.text_area :description, rows: 8, class: 'form-control', placeholder: "Enter topic description" %>
  <% end %>

  <div class="form-group">
    <%= f.label :public, class: 'checkbox' do %>
      <%= f.check_box :public %> Public topic
    <% end %>
  </div>

  <%= f.submit "Save", class: 'btn btn-success' %>

<% end %>

app/views/topics/edit.html.erb
<h1>Edit Topic</h1>

<div class="row">

  <div class="col-md-4">
    <p>Guidelines for topics:</p>
    <ul>
      <li>Make sure the topic is appropriate.</li>
      <li>Never insult dogs.</li>
      <li>Smile when you type.</li>
    </ul>
  </div>

  <div class="col-md-8">
    <%= render partial: 'form', locals: { topic: @topic } %>
  </div>

</div>

app/views/topics/index.html.erb
<h1>Topics</h1>

<div class="row">
    <div class="col-md-8">
        <!-- Loop over each topic in @topics -->
        <% @topics.each do |topic| %>
            <div class="media">
                <div class="media-body">
                    <h4 class="media-heading">
                        <!-- Create link to the show view for each topic -->
                        <%= link_to topic.name, topic %>
                    </h4>
                    <small>
             <%= topic.description %>
           </small>
                </div>
            </div>
            <% end %>
    </div>
    <div class="col-md-4">
        <!-- Create a link to a new topic -->
        <%= link_to "New Topic", new_topic_path, class: 'btn btn-success' %>
    </div>
</div>

app/views/topics/new.html.erb
<h1>New Topic</h1>

<div class="row">

  <div class="col-md-4">
    <p>Guidelines for topics:</p>
    <ul>
      <li>Make sure the topic is appropriate.</li>
      <li>Never insult dogs.</li>
      <li>Smile when you type.</li>
    </ul>
  </div>

  <div class="col-md-8">
    <%= render partial: 'form', locals: { topic: @topic } %>
  </div>

</div>

app/views/topics/show.html.erb
<h1>
    <%= @topic.name %>
</h1>

<%= link_to "Edit Topic", edit_topic_path, class: 'btn btn-success' %>
    <%= link_to "Delete Topic", @topic, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this topic?' } %>


        <div class="row">
            <div class="col-md-8">
                <p class="lead">
                    <%= @topic.description %>
                </p>
                <!--iterate over post belonging to @topic and display each post-->
                <% @topic.posts.each do |post| %>
                    <div class="media">
                        <div class="media-body">
                            <h4 class="media-heading">
                            <!-- link to individual posts using the topic_post_path method. This helper takes a topic and a post and generates a path to the posts show view-->
                            <%= link_to post.title, topic_post_path(@topic, post) %>
                            </h4>
                            <!--add submission and comment details for each post in the show view-->
                            <small>
                            submitted <%= time_ago_in_words(post.created_at) %> ago <br>
                            <%= post.comments.count %> Comments
                          </small>
                        </div>
                    </div>
                    <% end %>
            </div>
            <div class="col-md-4">
                     <%= link_to "New Post", new_topic_post_path(@topic), class: 'btn btn-success' %>
            </div>
        </div>