config/routes.rb
Rails.application.routes.draw do

  #GOT RID OF IN CHECKPOINT 21-resources :topics #didn't pass in any action arguments into controller generator; resources creates seven standard CRUD routes for me (index, create, new, edit, show, update PUT, update PATCH, destroy)
  #GOT RID OF IN CHECKPOINT 21-resources :posts #call the resources method and pass it a symbol; instructs Rails to create post routes for creating, updating, viewing, and deleting instances of Post

  resources :topics do
    #pass resources :posts to the resources :topics block. This nests the post routes under the topic routes
    resources :posts, except: [:index]
  end

  #create user routes for new and create actions; only hash key will prevent Rails from creating unnecessary routes
  resources :users, only: [:new, :create]

  resources :sessions, only: [:new, :create, :destroy]

  post 'users/confirm' => 'users#confirm'

  get 'about' => 'welcome#about' #remove get "welcome/index" because we've declared the index view as the root view; also modify the about route to allow users to visit /about, rather than /welcome/about

  root 'welcome#index'#root method allows us to declare the default page; index will be the first thing we see

end

#TO GET ALL ROUTES IN TERMINAL...
  ##rails routes
#TO GET TOPICS ROUTES
  ##rails routes | grep topics
#TO GET USER ROUTES
  ##rails routes | grep user
#TO GET SESSION ROUTES
    ##rails routes | grep session

app/models/post.rb
#Controls the post attributes passed into db
#http://guides.rubyonrails.org/active_record_validations.html

class Post < ActiveRecord::Base #My validation tests fail if Post < ApplicationRecord???
    #Because comments already depend on posts, they will also be deleted when a topic is deleted.
    belongs_to :topic
    #allows a post instance to have many comments related to it,  also provides methods that allow comment retrieval; similar to way attr_accessor generates 'getter' and 'setter' methods for instance variables; destroying post also creates cascade deletion that will destroy its comments too
    has_many :comments, dependent: :destroy 

    validates :title, length: { minimum: 5 }, presence: true
    validates :body, length: { minimum: 20 }, presence: true
    validates :topic, presence: true
end

app/controllers/posts_controller.rb
#DEFINES THE ACTIONS OF POSTS

class PostsController < ApplicationController

  #Got rid of index method once topic logic was in place

  def show
    @post = Post.find(params[:id]) #find the post that corresponds to the id in the params that was passed to show and assign it to @post. Unlike in the index method, in the show method, we populate an instance variable with a single post, rather than a collection of posts
  end

  def new
    @topic = Topic.find(params[:topic_id])
    @post = Post.new #create an instance variable, @post, then assign it an empty post returned by Post.new
  end

  def create #no view for create, works behind scenes- POST method
        #call Post.new to create new instance of Post
        @post = Post.new 
        @post.title = params[:post][:title]
        @post.body = params[:post][:body]
        #define topic
        @topic = Topic.find(params[:topic_id])
        #assign topic to post
        @post.topic = @topic
   
        if @post.save #if post successfully saved to DB, show a success method using flash[:notice] and redirect user to route generated by @post- will take user into show view
          flash[:notice] = "Post was saved."
          #redirects to nested topic/post path
          redirect_to [@topic, @post]
        else 
          #if save doesn't work, flash error message and render the new view again
          flash.now[:alert] = "There was an error saving the post. Please try again."
          render :new
        end
  end

  def edit
    @post = Post.find(params[:id]) #find the edit method by the post's id, then perform whatever logic
  end

  def update
    @post = Post.find(params[:id]) #find post id and assign to @post
    @post.title = params[:post][:title] #pass title to @post
    @post.body = params[:post][:body] #pass body to @post

    if @post.save 
      #if @post is saved, flash saved notice and redirect to @post
      flash[:notice] = "Post was updated."
      #redirects to nested topic/post path
      redirect_to [@post.topic, @post]
    else 
      #if @post doesn't save, flash an alert and go back to the edit view
      flash.now[:alert] = "There was an error saving the post. Please try again."
      render :edit
    end
  
  end

  def destroy
    
    @post = Post.find(params[:id]) #find @post by the post's id

    if @post.destroy #destroy is like the opposite of generate; don't have to enter in the title and body, just find the id and Rails will do the rest
      flash[:notice] = "\"#{@post.title}\" was deleted successfully."
      #when post is deleted, redirect to topic show view
      redirect_to @post.topic
    else
      flash.now[:alert] = "There was an error deleting the post."
      render :show #goes back to showing individual post
    end
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<!--Partial for post views; underscore before file name lets rails know it's a partial-->
<!--Partials can use instance variables, but for cleanliness and reusability it's better to use locals -->

<%= form_for [topic, post] do |f| %>
    <% if post.errors.any? %>

      <div class="alert alert-danger">

        <h4> <%= pluralize(post.errors.count, "error") %>.</h4>
            <ul>
              <% post.errors.full_messages.each do |msg| %>
                <li>
                  <%= msg %>
                </li>
              <% end %>
            </ul>
      </div>
    <% end %>

    <%= form_group_tag(post.errors[:title]) do %>
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control', placeholder: "Enter post title" %>
    <% end %>

    <%= form_group_tag(post.errors[:body]) do %>
      <%= f.label :body %>
      <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter post body" %>
    <% end %>

    <div class="form-group">
      <%= f.submit "Save", class: 'btn btn-success' %>
    </div>

<% end %>

app/views/posts/edit.html.erb
<!--View lets you edit a post, takes its orders from controllers/post_controller.rb-->

<h1>Edit Post</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for posts</p>
      <ul>
        <li>Make sure it rhymes.</li>
        <li>Don't use the letter "A".</li>
        <li>The incessant use of hashtags will get you banned.</li>
      </ul>
  </div>

  <div class="col-md-8">
    <!--replaced a large chunk of code with a partial (http://guides.rubyonrails.org/layouts_and_rendering.html#using-partials) -->
    <%= render partial: 'form', locals: { topic: @post.topic, post: @post } %>
  </div>

</div>

app/views/posts/new.html.erb
<!--New post view; uses form_for to render, which like link_to is another Rails helper method that generates HTML-->
<h1>New Post</h1>

<div class="row">

  <div class="col-md-4">
    <p>Guidelines for posts</p>
      <ul>
        <li>Make sure it rhymes.</li>
          <li>Don't use the letter "A".</li>
          <li>The incessant use of hashtags will get you banned.</li>
      </ul>
  </div>

  <div class="col-md-8">
    <%= render partial: 'form', locals: { topic: @topic, post: @post } %>
  </div>

</div>

app/views/posts/show.html.erb
<!--Shows an individual post in view, takes its orders from controllers/post_controller.rb-->

<h1>
    <%= @post.title %>
</h1>

<div class="row">
    <div class="col-md-8">
        <p>
            <%= @post.body %>
        </p>
    </div>
    <div class="col-md-4">
        <%= link_to "Edit", edit_topic_post_path(@post.topic, @post), class: 'btn btn-success' %>
        <%= link_to "Delete Post", [@post.topic, @post], method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this post?' } %>
    </div>
</div>