config/routes.rb
Rails.application.routes.draw do

  #GOT RID OF IN CHECKPOINT 21-resources :topics #didn't pass in any action arguments into controller generator; resources creates seven standard CRUD routes for me (index, create, new, edit, show, update PUT, update PATCH, destroy)
  #GOT RID OF IN CHECKPOINT 21-resources :posts #call the resources method and pass it a symbol; instructs Rails to create post routes for creating, updating, viewing, and deleting instances of Post

  resources :topics do
    #pass resources :posts to the resources :topics block. This nests the post routes under the topic routes
    resources :posts, except: [:index]
  end

  #create user routes for new and create actions; only hash key will prevent Rails from creating unnecessary routes
  resources :users, only: [:new, :create]

  resources :sessions, only: [:new, :create, :destroy]

  post 'users/confirm' => 'users#confirm'

  get 'about' => 'welcome#about' #remove get "welcome/index" because we've declared the index view as the root view; also modify the about route to allow users to visit /about, rather than /welcome/about

  root 'welcome#index'#root method allows us to declare the default page; index will be the first thing we see

end

#TO GET ALL ROUTES IN TERMINAL...
  ##rails routes
#TO GET TOPICS ROUTES
  ##rails routes | grep topics
#TO GET USER ROUTES
  ##rails routes | grep user
#TO GET SESSION ROUTES
    ##rails routes | grep session

app/views/layouts/application.html.erb
<!--Will always render in app, no matter the particular view-->

<!DOCTYPE html>
<html>

<head>
    <title>Bloccit</title>
    <%= csrf_meta_tags %>

        <meta name="viewport" content="width=device-width, initial-scale=1">
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
            <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>

    <div class="container">
        <ul class="nav nav-tabs">
            <li><%= link_to "Bloccit", root_path %></li>
            <li><%= link_to "Topics", topics_path %></li>
            <li><%= link_to "About", about_path %></li>
            <% if current_user %>
              <li class="pull-right"><%= link_to "#{current_user.name} -Sign Out", session_path(current_user), method: :delete %></li>
            <% else %>
              <li class="pull-right"><%= link_to "Sign In", new_session_path %></li>
              <li class="pull-right"><%= link_to "Sign Up", new_user_path %></li>
            <% end %>
        </ul>

        <!--For more info on alert, close, and the like: https://getbootstrap.com/docs/3.3/javascript/-->
        <% if flash[:notice] %>
            <div class="alert alert-success">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <%= flash[:notice] %>
            </div>
            <% elsif flash[:alert] %>
                <div class="alert alert-warning">
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                    <%= flash[:alert] %>
                </div>
                <% end %>
                    <%=yield%>

    </div>

</body>

</html>